package com.tatrafone.dataobjects;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Request from Client")
@org.kie.api.definition.type.Description("Every prospective client (partner, distributor) that wants to become a member of the alliance must fill request on the alliance portal.")
public class ClientRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public ClientRequest()
   {
   }

}