package com.tatrafone.dataobjects;

import com.tatrafone.dataobjects.ClientRequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Status Evaluation")
@org.kie.api.definition.type.Description("Evaluation of the client from the Sales Representative")
public class StatusEvaluation extends ClientRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public StatusEvaluation()
   {
   }

}