package com.tatrafone.dataobjects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EvaluationStatus implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EvaluationStatus() {
    }

}