package fi.muni.pv207.tatrafone.processes.ppc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CampaignRequirement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Only Czech language?")
   private java.lang.String czechReq;
   @org.kie.api.definition.type.Label(value = "Deadline")
   private java.util.Date deadline;
   @org.kie.api.definition.type.Label(value = "Name of the campaign")
   private java.lang.String campaignName;
   @org.kie.api.definition.type.Label(value = "Motto of the campaign")
   private java.lang.String motto;

   public CampaignRequirement()
   {
   }

   public java.lang.String getCzechReq()
   {
      return this.czechReq;
   }

   public void setCzechReq(java.lang.String czechReq)
   {
      this.czechReq = czechReq;
   }

   public java.util.Date getDeadline()
   {
      return this.deadline;
   }

   public void setDeadline(java.util.Date deadline)
   {
      this.deadline = deadline;
   }

   public java.lang.String getCampaignName()
   {
      return this.campaignName;
   }

   public void setCampaignName(java.lang.String campaignName)
   {
      this.campaignName = campaignName;
   }

   public java.lang.String getMotto()
   {
      return this.motto;
   }

   public void setMotto(java.lang.String motto)
   {
      this.motto = motto;
   }

   public CampaignRequirement(java.lang.String czechReq,
         java.util.Date deadline, java.lang.String campaignName,
         java.lang.String motto)
   {
      this.czechReq = czechReq;
      this.deadline = deadline;
      this.campaignName = campaignName;
      this.motto = motto;
   }

}