package fi.muni.pv207.tatrafone.processes.ppc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CampaignRequirement implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CampaignRequirement() {
    }

}