package tatrafone;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("TestObject1")
@org.kie.api.definition.type.Description("Moj prvy")
public class TestObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Ratac")
   private java.lang.Float ratac;

   public TestObject()
   {
   }

   public java.lang.Float getRatac()
   {
      return this.ratac;
   }

   public void setRatac(java.lang.Float ratac)
   {
      this.ratac = ratac;
   }

   public TestObject(java.lang.Float ratac)
   {
      this.ratac = ratac;
   }

}